# Generated by Django 3.2.8 on 2021-10-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
                ('observacoes', models.CharField(max_length=100, verbose_name='Observaçoes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
